name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build C#
        run: dotnet build

      - name: Test C#
        run: dotnet test

      - name: install dependencies
        run: npm install
        working-directory: ./DotnetTemplate.Web

      - name: Build TypeScript
        run: npm run build
        working-directory: ./DotnetTemplate.Web

      - name: Run linter
        run: npm run lint
        working-directory: ./DotnetTemplate.Web
